apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: IMAGE_PLACEHOLDER
    newName: ACCOUNT_ID.dkr.ecr.ap-northeast-2.amazonaws.com/wins-assist
    newTag: latest  # ArgoCD image updater가 자동 교체
