apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: IMAGE_PLACEHOLDER
    newName: 025913801970.dkr.ecr.ap-northeast-2.amazonaws.com/dyyeom-llm
    newTag: 7d38a91777ed9fae992eb15cef06ee937c65dd32
